name: holamundo_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^1.10.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fondoflutter.jpg  # Ruta de la imagen de fondo

  # Aquí puedes definir configuraciones adicionales como fuentes personalizadas
  # fonts:
  #   - family: MyCustomFont
  #     fonts:
  #       - asset: assets/fonts/my_custom_font.ttf
